<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Description>Free Train Simulator Multiplayer Hub</Description>
		<AssemblyTitle>Free Train Simulator Multiplayer Hub</AssemblyTitle>
		<OutputPath>..\..\Program</OutputPath>
		<ApplicationIcon>..\FTS.ico</ApplicationIcon>
		<Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MagicOnion.Serialization.MemoryPack" Version="7.10.1-preview" />
		<PackageReference Include="MagicOnion.Server" Version="7.10.2" />
		<PackageReference Include="System.IO.Hashing" Version="10.0.11" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\FreeTrainSimulator.Online\FreeTrainSimulator.Online.csproj" />
	</ItemGroup>
</Project>
