// COPYRIGHT 2009, 2010, 2011, 2012, 2013 by the Open Rails project.
// 
// This file is part of Open Rails.
// 
// Open Rails is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Open Rails is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Open Rails.  If not, see <http://www.gnu.org/licenses/>.

/* AI
 * 
 * Contains code to initialize and control AI trains.
 * Currently, AI trains are created at startup and moved down 1000 meters to make them
 * invisible.  This is done so the rendering code can discover the model it needs to draw.
 * 
 * 
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;

using FreeTrainSimulator.Common;
using FreeTrainSimulator.Common.Calc;
using FreeTrainSimulator.Models.Content;
using FreeTrainSimulator.Models.Shim;

using Orts.Formats.Msts;
using Orts.Formats.Msts.Files;
using Orts.Formats.Msts.Models;
using Orts.Simulation.Multiplayer;
using Orts.Simulation.Multiplayer.Messaging;
using Orts.Simulation.RollingStocks;
using Orts.Simulation.RollingStocks.SubSystems;
using Orts.Simulation.Timetables;
using Orts.Simulation.Track;

namespace Orts.Simulation.AIs
{
    public class AI
    {
        private readonly Simulator simulator;
        public Collection<AITrain> AITrains { get; } = new Collection<AITrain>();// active AI trains

        public StartTrains StartList { get; } = new StartTrains(); // trains yet to be started
        public Collection<AITrain> AutoGenTrains { get; } = new Collection<AITrain>(); // auto-generated trains
        public double ClockTime { get; private set; } // clock time : local time before activity start, common time from simulator after start
        private bool localTime;  // if true : clockTime is local time
        public Collection<AITrain> TrainsToRemove { get; } = new Collection<AITrain>();
        public Collection<AITrain> TrainsToAdd { get; } = new Collection<AITrain>();
        public Collection<AITrain> TrainsToRemoveFromAI { get; } = new Collection<AITrain>();
        public bool TrainListChanged { get; set; } = true; // To indicate to TrainListWindow that the list has changed;

        /// <summary>
        /// Loads AI train information from activity file.
        /// Creates a queue of AI trains in the order they should appear.
        /// At the moment AI trains are also created off scene so the rendering code will know about them.
        /// </summary>
        public AI(Simulator simulator, double activityStartTime, CancellationToken cancellationToken)
        {
            this.simulator = simulator ?? throw new ArgumentNullException(nameof(simulator));
            if (simulator.ActivityFile != null && simulator.ActivityFile.Activity.Traffic != null)
            {
                foreach (var sd in simulator.ActivityFile.Activity.Traffic.Services)
                {
                    _ = CreateAITrain(sd, simulator.ActivityFile.Activity.Traffic.TrafficFile.TrafficDefinition, simulator.TimetableMode);
                    if (cancellationToken.IsCancellationRequested)
                        return;
                }
            }

            // prerun trains
            PrerunAI(cancellationToken);

            ClockTime = this.simulator.ClockTime;
            localTime = false;
        }

        // constructor for Timetable trains
        // trains allready have a number - must not be changed!
        public AI(Simulator simulator, List<TTTrain> allTrains, int playerTrainOriginalTrain, TimetableFormationCommand playerTrainFormedOfType, TTTrain playerTrain, CancellationToken cancellation)
        {
            this.simulator = simulator ?? throw new ArgumentNullException(nameof(simulator));

            foreach (var train in allTrains)
            {
                if (train.TrainType == TrainType.Player)
                {
                    train.AI = this;
                    AITrains.Add(train);
                    TrainListChanged = true;
                }
                else if (train.TrainType == TrainType.PlayerIntended)
                {
                    train.AI = this;
                    StartList.InsertTrain(train);
                    this.simulator.StartReference.Add(train.Number);
                }
                else if (train.TrainType == TrainType.AiAutoGenerated)
                {
                    train.AI = this;
                    train.BrakeSystem.BrakeLine3Pressure = 0;
                    AutoGenTrains.Add(train);
                    this.simulator.AutoGenDictionary.Add(train.Number, train);
                }

                // set train details
                else
                {
                    train.TrainType = TrainType.AiNotStarted;
                    train.AI = this;

                    if (train.Cars.Count > 0)
                        train.Cars[0].Headlight = HeadLightState.HeadlightOn;//AI train always has light on
                    train.BrakeSystem.BrakeLine3Pressure = 0;

                    // insert in start list

                    StartList.InsertTrain(train);
                    this.simulator.StartReference.Add(train.Number);
                }
            }

            // clear dictionary (no trains yet exist)
            this.simulator.TrainDictionary.Clear();
            this.simulator.NameDictionary.Clear();

            // prerun trains
            PrerunAI(playerTrainOriginalTrain, playerTrainFormedOfType, playerTrain, cancellation);

            localTime = false;
        }

        public AI(Simulator simulator)
        {
            this.simulator = simulator;
        }

        public void BeforeSnapshot()
        {
            RemoveTrains();   // remove trains waiting to be removed
            AddTrains();      // add trains waiting to be added
        }

        // prerun for activity mode
        private void PrerunAI(CancellationToken cancellation)
        {
            float firstAITime = StartList.NextTime;
            if (firstAITime > 0 && firstAITime < simulator.ClockTime)
            {
                Trace.WriteLine($"\n Run AI : {StartList.Count} ");

                // perform update for AI trains upto actual start time

                ClockTime = firstAITime - 1.0f;
                localTime = true;
                simulator.PreUpdate = true;

                for (double runTime = firstAITime; runTime < simulator.ClockTime; runTime += 5.0) // update with 5 secs interval
                {
                    int fullsec = Convert.ToInt32(runTime);
                    if (fullsec % 3600 == 0)
                        Trace.Write($" {fullsec / 3600:00}:00 ");

                    AIUpdate((float)(runTime - ClockTime), simulator.PreUpdate);
                    simulator.SignalEnvironment.Update(true);
                    ClockTime = runTime;
                    if (cancellation.IsCancellationRequested)
                        return;
                }
            }
        }


        // prerun for timetable mode
        private void PrerunAI(int playerTrainOriginalTrain, TimetableFormationCommand playerTrainFormedOfType, TTTrain playerTrain, CancellationToken cancellation)
        {
            bool endPreRun = false;

            float firstAITime = StartList.NextTime;
            if (firstAITime > 0 && firstAITime < simulator.ClockTime)
            {
                Trace.WriteLine($"\n Run AI : {StartList.Count} ");

                // perform update for AI trains upto actual start time

                ClockTime = firstAITime - 1.0f;
                localTime = true;
                simulator.PreUpdate = true;
                bool activeTrains = false;
                for (double runTime = firstAITime; runTime < simulator.ClockTime && !endPreRun; runTime += 5.0) // update with 5 secs interval
                {
                    var loaderSpan = (float)TimetableInfo.PlayerTrainOriginalStartTime - firstAITime;
                    simulator.TimetableLoadedFraction = ((float)runTime - firstAITime) / loaderSpan;

                    int fullsec = Convert.ToInt32(runTime);
                    if (fullsec % 3600 < 5)
                        Trace.Write($" {(fullsec / 3600):00}:00 ");

                    endPreRun = AITTUpdate((float)(runTime - ClockTime), simulator.PreUpdate, ref activeTrains);

                    if (activeTrains)
                    {
                        simulator.SignalEnvironment.Update(true);
                    }

                    ClockTime = runTime;
                    if (cancellation.IsCancellationRequested)
                        return;
                }

                // prerun finished - check if train from which player train originates has run and is finished
                bool delayedrun = false;
                bool OrgTrainNotStarted = false;
                TTTrain OrgTrain = null;
                TTTrain PlayTrain = null;

                // player train is pre-created - check if it exists already
                if (playerTrainFormedOfType == TimetableFormationCommand.Created)
                {
                    PlayTrain = simulator.Trains.GetAITrainByNumber(0) as TTTrain;
                    // train exists - set as player train
                    if (PlayTrain != null)
                    {
                        PlayTrain.TrainType = TrainType.Player;
                        PlayTrain.MovementState = AiMovementState.Init;
                    }
                    else
                    {
                        Trace.TraceInformation("Player train start delayed as track is not clear");
                        delayedrun = true;

                        // reset formed state as train can now be started directly
                        playerTrainOriginalTrain = -1;
                    }
                }

                // player train is extracted from pool
                else if (!String.IsNullOrEmpty(playerTrain.CreateFromPool))
                {
                    TimetablePool.TrainFromPool extractResult = TimetablePool.TrainFromPool.Failed;
                    if (simulator.PoolHolder.Pools.TryGetValue(playerTrain.CreateFromPool, out TimetablePool timetablePool))
                    {
                        int presentTime = Convert.ToInt32(Math.Floor(ClockTime));
                        extractResult = timetablePool.ExtractTrain(ref playerTrain, presentTime);
                    }
                    else
                    {
                        Trace.TraceError("Player train {0} : Invalid pool definition : {1} : pool not found", playerTrain.Name, playerTrain.CreateFromPool);
                    }

                    // switch on outcome
                    switch (extractResult)
                    {
                        // train formed : no further action
                        case TimetablePool.TrainFromPool.Formed:
                            break;

                        // train creation failed : no need to try again (will fail again), so abandone
                        case TimetablePool.TrainFromPool.Failed:
                            throw new InvalidDataException("Session aborted - cannot extract required engine from pool");

                        // not created but not failed : hold, try again in 30 secs.
                        case TimetablePool.TrainFromPool.NotCreated:
                            delayedrun = true;
                            break;

                        // forced created away from pool : create train
                        case TimetablePool.TrainFromPool.ForceCreated:
                            break;
                    }
                }

                // player train is formed out of other train
                else if (playerTrainOriginalTrain > 0 && (playerTrainFormedOfType == TimetableFormationCommand.TerminationFormed || playerTrainFormedOfType == TimetableFormationCommand.TerminationTriggered))
                {
                    OrgTrainNotStarted = simulator.Trains.CheckTrainNotStartedByNumber(playerTrainOriginalTrain);
                    OrgTrain = simulator.Trains.GetAITrainByNumber(playerTrainOriginalTrain) as TTTrain;
                    if (OrgTrainNotStarted)
                    {
                        Trace.TraceInformation("Player train start delayed as incoming train has yet to start");
                        delayedrun = true;
                    }
                    else if (OrgTrain != null)
                    {
                        Trace.TraceInformation("Player train start delayed as incoming train {0} [{1}] has not yet arrived", OrgTrain.Name, OrgTrain.Number);
                        if (OrgTrain.Delay.HasValue)
                        {
                            Trace.TraceInformation("Last Reported delay : {0}", OrgTrain.Delay.Value.ToString());
                        }
                        delayedrun = true;
                    }
                }

                // if player train is detached from other train
                else if (playerTrainOriginalTrain > 0 && playerTrainFormedOfType == TimetableFormationCommand.Detached)
                {
                    PlayTrain = simulator.Trains.GetAITrainByNumber(0) as TTTrain;
                    // train exists - set as player train
                    if (PlayTrain != null)
                    {
                        PlayTrain.TrainType = TrainType.Player;
                        PlayTrain.MovementState = AiMovementState.Init;
                    }
                    else
                    {
                        OrgTrainNotStarted = simulator.Trains.CheckTrainNotStartedByNumber(playerTrainOriginalTrain);
                        PlayTrain = simulator.Trains.GetAITrainByNumber(playerTrainOriginalTrain) as TTTrain;

                        if (OrgTrainNotStarted || OrgTrain == null)
                        {
                            Trace.TraceInformation("Player train start delayed as original train has yet to start");
                            delayedrun = true;
                        }
                        else
                        {
                            Trace.TraceInformation("Player train start delayed as original train has not yet arrived");
                            delayedrun = true;
                        }
                    }
                }

                // if player train exists but cannot be placed or has no power 
                else if (playerTrain != null)
                {
                    if (playerTrain.CalculateInitialTrainPosition().Count == 0)
                    {
                        delayedrun = true;
                        Trace.TraceInformation("Player train start delayed as track is not clear");
                    }

                    if (playerTrain.LeadLocomotive == null)
                    {
                        delayedrun = true;
                        Trace.TraceInformation("Player train start delayed as train has no power");
                    }
                }

                // if player train exists, also check if it has an engine
                if (!delayedrun && playerTrain != null)
                {
                    if (simulator.PlayerLocomotive == null)
                    {
                        delayedrun = true;
                        Trace.TraceInformation("Player train start delayed as train has no power");
                    }
                }

                // continue prerun until player train can be started
                if (delayedrun)
                {
                    bool dummy = true;  // dummy boolead for ActiveTrains

                    float deltaTime = 5.0f; // update with 1 sec. interval
                    double runTime = simulator.ClockTime - (double)deltaTime;
                    bool playerTrainStarted = false;

                    while (!playerTrainStarted)
                    {
                        endPreRun = AITTUpdate((float)(runTime - ClockTime), simulator.PreUpdate, ref dummy);
                        simulator.SignalEnvironment.Update(true);
                        ClockTime = runTime;
                        runTime += deltaTime;
                        if (cancellation.IsCancellationRequested)
                            return;

                        int fullsec = Convert.ToInt32(runTime);
                        if (fullsec % 3600 == 0)
                            Trace.Write($" {(fullsec / 3600):00}:00 ");

                        if (runTime >= 24 * 3600) // end of day reached
                        {
                            if (playerTrainOriginalTrain > 0)
                            {
                                if (OrgTrainNotStarted)
                                {
                                    throw new InvalidDataException("Session aborted - incoming train has not run at all");
                                }
                                else
                                {
                                    throw new InvalidDataException("Session aborted - incoming train has not arrived before midnight");
                                }
                            }
                            else
                            {
                                throw new InvalidDataException("Session aborted - track for player train not cleared before midnight");
                            }
                        }

                        if (playerTrainOriginalTrain > 0 && (playerTrainFormedOfType == TimetableFormationCommand.TerminationFormed || playerTrainFormedOfType == TimetableFormationCommand.TerminationTriggered))
                        {
                            OrgTrainNotStarted = simulator.Trains.CheckTrainNotStartedByNumber(playerTrainOriginalTrain);
                            OrgTrain = simulator.Trains.GetAITrainByNumber(playerTrainOriginalTrain) as TTTrain;
                            playerTrainStarted = (!OrgTrainNotStarted && OrgTrain == null);
                        }
                        else if (playerTrainOriginalTrain > 0 && playerTrainFormedOfType == TimetableFormationCommand.Detached)
                        {
                            PlayTrain = simulator.Trains.GetAITrainByNumber(0) as TTTrain;
                            // train exists - set as player train
                            playerTrainStarted = (PlayTrain != null);

                            if (playerTrain.LeadLocomotive == null)
                            {
                                playerTrainStarted = false;
                            }
                        }
                        else
                        {
                            playerTrainStarted = playerTrain.CalculateInitialTrainPosition().Count > 0;
                        }
                    }

                    TimeSpan delayedStart = new TimeSpan((long)(Math.Pow(10, 7) * (ClockTime - simulator.ClockTime)));
                    Trace.TraceInformation("Start delayed by : {0}", delayedStart.ToString());
                    StartList.RemovePlayerTrain();
                    TTTrain playerTTTrain = playerTrain as TTTrain;
                    playerTTTrain.InitalizePlayerTrain();
                    simulator.ClockTime = runTime;
                }
                else
                {
                    // remove player train from start list
                    StartList.RemovePlayerTrain();

                    Trace.TraceInformation("Player train started on time");
                    TTTrain playerTTTrain = playerTrain as TTTrain;
                    playerTTTrain.InitalizePlayerTrain();
                }
            }

            // no AI trains ahead of player train 
            else
            {
                // remove player train from start list
                StartList.RemovePlayerTrain();

                Trace.TraceInformation("Player train started on time");
                TTTrain playerTTTrain = playerTrain as TTTrain;
                playerTTTrain.InitalizePlayerTrain();

                ClockTime = simulator.ClockTime = playerTTTrain.StartTime.Value;
            }

            Trace.Write("\n");
            simulator.PreUpdate = false;
        }

        /// <summary>
        /// Updates AI train information - activity mode
        /// Creates any AI trains that are scheduled to appear.
        /// Moves all active AI trains by calling their Update method.
        /// And finally, removes any AI trains that have reached the end of their path.
        /// </summary>
        public void ActivityUpdate(double elapsedClockSeconds)
        {
            AIUpdate(elapsedClockSeconds, false);
        }

        public void AIUpdate(double elapsedClockSeconds, bool preUpdate)
        {
            // update clock

            if (!localTime)
            {
                ClockTime = simulator.ClockTime;
            }

            // check to see if any train to be added

            float nextTrainTime = StartList.NextTime;
            if (nextTrainTime > 0 && nextTrainTime < ClockTime)
            {
                Collection<AITrain> newTrains = StartList.GetTrains((float)ClockTime);
                foreach (AITrain thisTrain in newTrains)
                {
                    simulator.StartReference.Remove(thisTrain.Number);
                    var validPosition = AddToWorld(thisTrain);
                    if (thisTrain.InitialSpeed > 0 && validPosition)
                    // Add extra run to allow setting signals
                    {
                        thisTrain.AIPreUpdate(0);
                    }
                }
            }
            foreach (AITrain train in AITrains)
            {
                if (train.TrainType != TrainType.AiIncorporated && (train.Cars.Count == 0 && train.TrainType != TrainType.AiIncorporated || train.Cars[0].Train != train))
                    TrainsToRemove.Add(train);
                else
                    train.AIUpdate(elapsedClockSeconds, ClockTime, preUpdate);
            }

            RemoveTrains();
            RemoveFromAITrains();
            AddTrains();
        }

        // used in timetable mode
        public void TimetableUpdate(double elapsedClockSeconds)
        {
            bool dummy = true; // dummy for activeTrains boolean
            AITTUpdate(elapsedClockSeconds, false, ref dummy);
        }

        public bool AITTUpdate(double elapsedClockSeconds, bool preUpdate, ref bool activeTrains)
        {
            bool endPreRun = false;
            // update clock

            if (!localTime)
            {
                ClockTime = simulator.ClockTime;
            }

            // check to see if any train to be added

            float nextTrainTime = StartList.NextTime;
            if (nextTrainTime > 0 && nextTrainTime < ClockTime)
            {
                Collection<TTTrain> newTrains = StartList.GetTTTrains((float)ClockTime);

                foreach (TTTrain thisTrain in newTrains)
                {
                    simulator.StartReference.Remove(thisTrain.Number);
                    if (thisTrain.TrainType == TrainType.AiNotStarted)
                        thisTrain.TrainType = TrainType.Ai;
                    endPreRun = AddToWorldTT(thisTrain, newTrains);
                    if (endPreRun)
                        break;
                }
            }

            // check if any active trains

            if (!activeTrains)
            {
                foreach (AITrain acttrain in AITrains)
                {
                    TTTrain actTTTrain = acttrain as TTTrain;
                    if (acttrain.MovementState != AiMovementState.Static && acttrain.TrainType != TrainType.Player)
                    {
                        activeTrains = true;
                        break;
                    }
                    else if (acttrain.MovementState == AiMovementState.Static && actTTTrain.ActivateTime < ClockTime)
                    {
                        activeTrains = true;
                        break;
                    }
                }
            }

            if (activeTrains || TrainsToAdd.Count > 0)
            {
                if (preUpdate)
                {
                    float intervalTime = 0.5f;

                    for (float trainUpdateTime = 0; trainUpdateTime < elapsedClockSeconds && !endPreRun; trainUpdateTime += intervalTime)
                    {
                        ClockTime += intervalTime;
                        nextTrainTime = StartList.NextTime;
                        if (nextTrainTime > 0 && nextTrainTime < ClockTime)
                        {
                            Collection<TTTrain> newTrains = StartList.GetTTTrains((float)ClockTime);

                            foreach (TTTrain thisTrain in newTrains)
                            {
                                simulator.StartReference.Remove(thisTrain.Number);
                                if (thisTrain.TrainType == TrainType.AiNotStarted)
                                    thisTrain.TrainType = TrainType.Ai;
                                endPreRun = AddToWorldTT(thisTrain, newTrains);
                                if (endPreRun)
                                    break;
                            }
                        }

                        foreach (var train in AITrains)
                        {
                            if (train.TrainType != TrainType.Player && train.TrainType != TrainType.PlayerIntended)
                            {
                                if (train.Cars.Count == 0 || train.Cars[0].Train != train)
                                {
                                    TrainsToRemove.Add(train);
                                }
                                else
                                {
                                    train.AIUpdate(intervalTime, ClockTime, preUpdate);
                                }
                            }
                            else if (train.TrainType == TrainType.PlayerIntended && train.MovementState == AiMovementState.Static)
                            {
                                TTTrain trainTT = train as TTTrain;
                                int presentTime = Convert.ToInt32(Math.Floor(ClockTime));
                                trainTT.UpdateAIStaticState(presentTime);
                            }
                        }

                        RemoveTrains();
                        RemoveFromAITrains();
                        AddTTTrains();
                    }
                }
                else
                {
                    foreach (var train in AITrains)
                    {
                        if (train.TrainType != TrainType.Player)
                        {
                            if (train.Cars.Count == 0 || train.Cars[0].Train != train)
                            {
                                TrainsToRemove.Add(train);
                            }
                            else
                            {
                                train.AIUpdate(elapsedClockSeconds, ClockTime, preUpdate);
                            }
                        }
                    }
                    RemoveTrains();
                    RemoveFromAITrains();
                    AddTTTrains();
                }
            }
            return (endPreRun);
        }

        /// <summary>
        /// Creates an AI train
        /// </summary>
        private AITrain CreateAITrain(Services sd, ServiceTraffic trd, bool isTimetableMode)
        {
            // set up a new AI train
            // first extract the service definition from the activity file
            // this gives the consist and path

            // find related traffic definition

            ServiceTraffics trfDef = null;
            foreach (ServiceTraffics thisDef in trd.ServiceTraffics)
            {
                if (string.Equals(thisDef.Name, sd.Name, StringComparison.OrdinalIgnoreCase) &&
                thisDef.Time == sd.Time)
                {
                    trfDef = thisDef;
                    break;
                }
            }
            ServiceFile srvFile = new ServiceFile(simulator.RouteFolder.ServiceFile(sd.Name));  // read service file
            AITrain train = CreateAITrainDetail(sd, trfDef, srvFile, isTimetableMode, false);
            if (train != null)
            {
                // insert in start list

                StartList.InsertTrain(train);
                simulator.StartReference.Add(train.Number);
            }
            return train;
        }

        /// <summary>
        /// Creates the detail of an AI train
        /// Moves the models down 1000M to make them invisible.
        /// called also in case of autopilot mode
        /// </summary>
        public AITrain CreateAITrainDetail(Services sd, ServiceTraffics trfDef, ServiceFile srvFile, bool isTimetableMode, bool isInitialPlayerTrain)
        {
            // read consist file

            string consistFileName = simulator.RouteFolder.ContentFolder.ConsistFile(srvFile.TrainConfig);
            ConsistFile conFile = new ConsistFile(consistFileName);

            PathModel pathModel = Task.Run(async() => await (await Simulator.Instance.RouteModel.GetPaths(CancellationToken.None).ConfigureAwait(false)).GetById(srvFile.PathId.Trim()).GetExtended(CancellationToken.None).ConfigureAwait(false)).Result;
            AIPath aiPath = new AIPath(pathModel, isTimetableMode);

            if (aiPath.Nodes == null)
            {
                Trace.TraceWarning($"Invalid path {pathModel?.Hierarchy() ?? simulator.RouteFolder.PathFile(srvFile.PathId)} for AI train : " + srvFile.Name + " ; train not started\n");
                return null;
            }

            float maxVelocityA = conFile.Train.MaxVelocity.A;
            // sd.Name is the name of the service file.
            // srvFile.Name points to the name of the service within the Name() category such as Name ( "Eastbound Freight Train" ) in the service file.
            AITrain train = new AITrain(sd, this, aiPath, srvFile.Efficiency, srvFile.Name, trfDef, maxVelocityA);
            simulator.TrainDictionary.Add(train.Number, train);

            if (!simulator.NameDictionary.ContainsKey(train.Name))
                simulator.NameDictionary.Add(train.Name, train);

            if (consistFileName.Contains("tilted", StringComparison.OrdinalIgnoreCase))
                train.IsTilting = true;

            // also set Route max speed for speedpost-processing in train.cs
            train.TrainMaxSpeedMpS = simulator.RouteModel.SpeedRestrictions[SpeedRestrictionType.Route];

            train.InitialSpeed = srvFile.TimeTable.InitialSpeed;

            if (maxVelocityA > 0 && train.Efficiency > 0)
            {
                // <CScomment> this is overridden if there are station stops
                train.TrainMaxSpeedMpS = Math.Min(train.TrainMaxSpeedMpS, maxVelocityA * train.Efficiency);
            }

            train.TcsParametersFileName = conFile.Train.TcsParametersFileName;

            // add wagons
            train.Length = 0.0f;
            foreach (Wagon wagon in conFile.Train.Wagons)
            {
                string wagonFilePath = simulator.RouteFolder.ContentFolder.WagonFile(wagon.Folder, wagon.Name);
                ;
                if (wagon.IsEngine)
                    wagonFilePath = Path.ChangeExtension(wagonFilePath, ".eng");
                else if (wagon.IsEOT)
                {
                    string wagonFolder = Path.Combine(simulator.RouteFolder.ContentFolder.Folder, "trains\\orts_eot", wagon.Folder);
                    wagonFilePath = wagonFolder + @"\" + wagon.Name + ".eot";
                }

                if (!File.Exists(wagonFilePath))
                {
                    Trace.TraceWarning($"Ignored missing {(wagon.IsEngine ? "engine" : "wagon")} {wagonFilePath} in consist {consistFileName}");
                    continue;
                }

                try
                {
                    TrainCar car = RollingStock.Load(train, wagonFilePath);
                    car.Flipped = wagon.Flip;
                    car.UiD = wagon.UiD;
                    car.FreightAnimations?.Load(wagon.LoadDataList);
                    train.Length += car.CarLengthM;
                    if (car is EndOfTrainDevice)
                    {
                        train.EndOfTrainDevice = car as EndOfTrainDevice;
                        if (!isInitialPlayerTrain)
                        {
                            train.EndOfTrainDevice.InitializeLevel();
                        }
                    }

                    if (isInitialPlayerTrain)
                    {
                        simulator.PathName = aiPath.PathName;
                        if (MultiPlayerManager.IsMultiPlayer())
                            car.CarID = MultiPlayerManager.UserName1 + " - " + car.UiD; //player's train is always named train 0.
                        else
                            car.CarID = "0 - " + car.UiD; //player's train is always named train 0.

                        if (simulator.ActivityModel != null && car is MSTSDieselLocomotive mstsDieselLocomotive)
                        {
                            mstsDieselLocomotive.DieselLevelL = mstsDieselLocomotive.MaxDieselLevelL * simulator.ActivityModel.FuelLevels[FuelType.Diesel] / 100.0f;
                        }

                        if (simulator.ActivityModel != null && car is MSTSSteamLocomotive mstsSteamLocomotive)
                        {
                            mstsSteamLocomotive.CombinedTenderWaterVolumeUKG = (float)((Mass.Kilogram.ToLb(mstsSteamLocomotive.MaxLocoTenderWaterMassKG) / 10.0) * simulator.ActivityModel.FuelLevels[FuelType.Water] / 100.0);
                            mstsSteamLocomotive.TenderCoalMassKG = mstsSteamLocomotive.MaxTenderCoalMassKG * simulator.ActivityModel.FuelLevels[FuelType.Coal] / 100.0f;
                        }

                        if (train.InitialSpeed != 0)
                            car.SignalEvent(PowerSupplyEvent.RaisePantograph, 1);
                    }
                    else
                    {
                        car.SignalEvent(PowerSupplyEvent.RaisePantograph, 1);
                        car.CarID = $"AI{train.Number} - {train.Cars.Count - 1}";
                    }

                    // associate location events
                    simulator.ActivityRun.AssociateEvents(train);

                }
                catch (Exception error)
                {
                    Trace.WriteLine(new FileLoadException(wagonFilePath, error));
                }

            }// for each rail car

            if (train.Cars.Count <= 0)
            {
                Trace.TraceInformation("Empty consists for AI train - train removed");
                return null;
            }

            train.Cars[0].Headlight = HeadLightState.HeadlightOn;//AI train always has light on

            // Patch placingproblem JeroenP (1 line)
            train.RearTDBTraveller = new Traveller(aiPath.FirstNode.Location, aiPath.FirstNode.NextMainNode.Location); // create traveller
            train.CreateRoute(false);  // create route without use of FrontTDBtraveller
            train.CheckFreight(); // check if train is freight or passenger
            train.SetDistributedPowerUnitIds(); // distributed power
            if (!isInitialPlayerTrain || train.InitialSpeed != 0)
                train.AITrainDirectionForward = true;
            train.BrakeSystem.BrakeLine3Pressure = 0;

            // Compute length of path to evaluate possibility of activity randomization
            if (simulator.UserSettings.ActivityRandomizationLevel > 0 && simulator.ActivityRun != null)
                train.PathLength = train.ComputePathLength();

            return train;
        }

        /// <summary>
        /// Add train to world : 
        /// place train on required position
        /// initialize signals and movement
        /// </summary>

        private bool AddToWorld(AITrain train)
        {
            // clear track and align switches - check state

            TrackCircuitPartialPathRoute tempRoute = train.CalculateInitialTrainPosition();
            bool validPosition = tempRoute.Count > 0;
            if (validPosition)
            {
                train.SetInitialTrainRoute(tempRoute);
                train.CalculatePositionOfCars();
                for (int i = 0; i < train.Cars.Count; i++)
                {
                    Microsoft.Xna.Framework.Vector3 position = train.Cars[i].WorldPosition.XNAMatrix.Translation;
                    position.Y -= 1000;
                    train.Cars[i].UpdateWorldPosition(train.Cars[i].WorldPosition.SetTranslation(position));
                }
                train.ResetInitialTrainRoute(tempRoute);
                validPosition = train.PostInit();
            }

            if (validPosition)
            {
                train.ActualWaitTimeS = 0; // reset wait counter //
                train.TrainType = TrainType.Ai;
                AITrains.Add(train);
                TrainListChanged = true;
                simulator.Trains.Add(train);
                simulator.TrainDictionary.Remove(train.Number); // clear existing entry
                simulator.TrainDictionary.Add(train.Number, train);
                simulator.NameDictionary.Remove(train.Name);
                simulator.NameDictionary.Add(train.Name, train);
                if (train.InitialSpeed > 0 && train.MovementState != AiMovementState.StationStop)
                {
                    train.InitializeMoving();
                    train.MovementState = AiMovementState.Braking;
                }
                else if (train.InitialSpeed == 0)
                {
                    train.InitializeBrakes();
                    train.AdjustControlsBrakeFull();
                }

                if (MultiPlayerManager.IsServer())
                {
                    MultiPlayerManager.Broadcast(new TrainStateMessage(train));
                }
            }
            else
            {
                train.StartTime += 30;    // try again in half a minute
                train.ActualWaitTimeS += 30;
                if (train.ActualWaitTimeS > 900)   // tried for 15 mins
                {
                    TimeSpan timeStart = new TimeSpan((long)(Math.Pow(10, 7) * train.StartTime.Value));
                    Trace.TraceWarning("Cannot place AI train {0} ({1}) at time {2}", train.Name, train.Number, timeStart.ToString());
                }
                else
                {
                    StartList.InsertTrain(train);
                    simulator.StartReference.Add(train.Number);
                }
            }

            return validPosition;
        }

        private bool AddToWorldTT(TTTrain thisTrain, Collection<TTTrain> nextTrains)
        {
            bool endPreRun = false;
            bool validPosition = true;
            TrackCircuitPartialPathRoute tempRoute = null;

            // create from pool
            if (!String.IsNullOrEmpty(thisTrain.CreateFromPool))
            {
                if (!simulator.PoolHolder.Pools.ContainsKey(thisTrain.CreateFromPool))
                {
                    Trace.TraceInformation("Train {0} : unknown pool defininion : {1} \n", thisTrain.Name, thisTrain.CreateFromPool);
                    thisTrain.CreateFromPool = String.Empty;
                }
            }

            if (!String.IsNullOrEmpty(thisTrain.CreateFromPool))
            {
                int presentTime = Convert.ToInt32(Math.Floor(ClockTime));

                TimetablePool thisPool = simulator.PoolHolder.Pools[thisTrain.CreateFromPool];
                TimetablePool.TrainFromPool poolResult = thisPool.ExtractTrain(ref thisTrain, presentTime);

                bool actionCompleted = false;

                // switch on outcome
                switch (poolResult)
                {
                    // train formed : no further action
                    case TimetablePool.TrainFromPool.Formed:
                        actionCompleted = true;
                        break;

                    // train creation delayed through incoming train
                    case TimetablePool.TrainFromPool.Delayed:
                        thisTrain.StartTime += 30;    // try again in half a minute
                        StartList.InsertTrain(thisTrain);
                        simulator.StartReference.Add(thisTrain.Number);
                        actionCompleted = true;
                        break;

                    // train creation failed : no need to try again (will fail again), so abandone
                    case TimetablePool.TrainFromPool.Failed:
                        actionCompleted = true;
                        break;

                    // not created but not failed : hold, try again in 30 secs.
                    case TimetablePool.TrainFromPool.NotCreated:
                        validPosition = false;
                        actionCompleted = false;
                        break;

                    // forced created away from pool : create train
                    case TimetablePool.TrainFromPool.ForceCreated:
                        validPosition = true;
                        actionCompleted = false;
                        tempRoute = thisTrain.CalculateInitialTTTrainPosition(ref validPosition, nextTrains);
                        break;
                }

                //Trace.TraceInformation("Train {0} from pool {1} : {2} \n", thisTrain.Name, thisPool.PoolName, poolResult.ToString());

                if (actionCompleted)
                    return (endPreRun);
            }

            // create in pool
            // note : train is placed in pool in outbound direction

            else if (!String.IsNullOrEmpty(thisTrain.CreateInPool))
            {
                // find place in pool
                int presentTime = Convert.ToInt32(Math.Floor(ClockTime));
                TimetablePool thisPool = simulator.PoolHolder.Pools[thisTrain.CreateInPool];


                int PoolStorageState = thisPool.CreateInPool(thisTrain, nextTrains);

                // if no storage available - abondone train
                if (PoolStorageState < 0)
                {
                    Trace.TraceInformation("Train : " + thisTrain.Name + " : no storage room available in pool : " + thisPool.PoolName + " ; engine not created");
                    return (endPreRun);
                }
            }

            // clear track and align switches - check state

            else
            {
                tempRoute = thisTrain.CalculateInitialTTTrainPosition(ref validPosition, nextTrains);
                if (validPosition)
                {
                    thisTrain.SetInitialTrainRoute(tempRoute);
                    thisTrain.CalculatePositionOfCars();
                    for (int i = 0; i < thisTrain.Cars.Count; i++)
                    {
                        Microsoft.Xna.Framework.Vector3 position = thisTrain.Cars[i].WorldPosition.XNAMatrix.Translation;
                        position.Y -= 1000;
                        thisTrain.Cars[i].UpdateWorldPosition(thisTrain.Cars[i].WorldPosition.SetTranslation(position));
                    }
                    thisTrain.ResetInitialTrainRoute(tempRoute);

                    validPosition = thisTrain.PostInit(false); // post init train but do not activate
                }
            }


            if (validPosition)
            {
                thisTrain.ActualWaitTimeS = 0; // reset wait counter //

                if (!AITrains.Contains(thisTrain))
                {
                    AITrains.Add(thisTrain);
                }

                if (thisTrain.TrainType != TrainType.PlayerIntended && thisTrain.TrainType != TrainType.Player) // player train allready exists
                {
                    simulator.Trains.Add(thisTrain);
                }

                if (thisTrain.TrainType == TrainType.PlayerIntended)
                {
                    thisTrain.TrainType = TrainType.Player;
                }

                simulator.TrainDictionary.Remove(thisTrain.Number); // clear existing entry
                simulator.TrainDictionary.Add(thisTrain.Number, thisTrain);
                simulator.NameDictionary.Remove(thisTrain.Name);
                simulator.NameDictionary.Add(thisTrain.Name, thisTrain);
            }
            else
            {
                TimeSpan timeStart = new TimeSpan((long)(Math.Pow(10, 7) * thisTrain.StartTime.Value));
                thisTrain.StartTime += 30;    // try again in half a minute
                thisTrain.ActualWaitTimeS += 30;
                if (thisTrain.ActualWaitTimeS > 900)   // tried for 15 mins
                {
                    timeStart = new TimeSpan((long)(Math.Pow(10, 7) * thisTrain.StartTime.Value));
                    Trace.TraceWarning("Cannot place AI train {0} ({1}) at time {2}", thisTrain.Number, thisTrain.Name, timeStart.ToString());
                }
                else
                {
                    StartList.InsertTrain(thisTrain);
                    simulator.StartReference.Add(thisTrain.Number);
                }
            }
            return (endPreRun);
        }

        /// <summary>
        /// Removes AI trains that have reached the end of their path or
        /// have been coupled onto by the player train.
        /// Moves the models down 1000M to make them invisible.
        /// </summary>
        private void RemoveTrains()
        {
            List<Physics.Train> removeList = new List<Physics.Train>();

            foreach (AITrain train in TrainsToRemove)
            {
                // check if train is actually still waiting to be added
                if (!TrainsToAdd.Remove(train))
                {
                    simulator.TrainDictionary.Remove(train.Number);
                    simulator.NameDictionary.Remove(train.Name);
                    AITrains.Remove(train);
                    simulator.Trains.Remove(train);
                    removeList.Add(train);
                    TrainListChanged = true;
                    if (train.Cars.Count > 0 && train.Cars[0].Train == train)
                    {
                        foreach (TrainCar car in train.Cars)
                        {
                            car.Train = null; // WorldPosition.XNAMatrix.M42 -= 1000;
                            car.IsPartOfActiveTrain = false;  // to stop sounds
                            // remove continers if any
                            if (car.FreightAnimations?.Animations != null)
                                car.FreightAnimations?.RemoveLoads();
                        }
                    }
                }
            }

            if (MultiPlayerManager.IsServer() && removeList.Count > 0)
            {
                MultiPlayerManager.Broadcast(new RemoveTrainMessage(removeList));
            }

            TrainsToRemove.Clear();
        }

        /// <summary>
        /// Removes an AI train only from the AI train list, but leaves it in the train lists

        /// </summary>
        private void RemoveFromAITrains()
        {

            foreach (AITrain train in TrainsToRemoveFromAI)
            {
                AITrains.Remove(train);
                TrainListChanged = true;
            }

            TrainsToRemoveFromAI.Clear();
        }

        private void AddTrains()
        {
            foreach (AITrain train in TrainsToAdd)
            {
                simulator.TrainDictionary.Remove(train.Number); // clear existing entry
                simulator.TrainDictionary.Add(train.Number, train);
                simulator.NameDictionary.Remove(train.Name);
                simulator.NameDictionary.Add(train.Name, train);
                AITrains.Add(train);
                TrainListChanged = true;
                if (train.TrainType != TrainType.PlayerIntended && train.TrainType != TrainType.Player)
                    simulator.Trains.Add(train);
            }
            TrainsToAdd.Clear();
        }

        private void AddTTTrains()
        {
            foreach (TTTrain train in TrainsToAdd)
            {
                simulator.TrainDictionary.Remove(train.Number); // clear existing entry
                simulator.TrainDictionary.Add(train.Number, train);
                simulator.NameDictionary.Remove(train.Name);
                simulator.NameDictionary.Add(train.Name, train);
                if (train.TrainType == TrainType.Player || train.TrainType == TrainType.PlayerIntended)
                {
                    AITrains.Insert(0, train);
                }
                else
                {
                    AITrains.Add(train);
                    simulator.Trains.Add(train);
                }
            }
            TrainsToAdd.Clear();
        }

    }

    public class StartTrains : LinkedList<AITrain>
    {

        //================================================================================================//
        //
        // Insert item on correct time
        //

        public void InsertTrain(AITrain thisTrain)
        {
            if (thisTrain.StartTime == null)
            {
                Trace.TraceInformation("Train : " + thisTrain.Name + " : missing start time, train not included");
                return;
            }

            if (this.Count == 0)
            {
                this.AddFirst(thisTrain);
            }
            else
            {
                LinkedListNode<AITrain> nextNode = this.First;
                AITrain nextTrain = nextNode.Value;
                bool inserted = false;
                while (!inserted)
                {
                    if (nextTrain.StartTime.Value > thisTrain.StartTime.Value)
                    {
                        this.AddBefore(nextNode, thisTrain);
                        inserted = true;
                    }
                    else if (nextNode.Next == null)
                    {
                        this.AddAfter(nextNode, thisTrain);
                        inserted = true;
                    }
                    else
                    {
                        nextNode = nextNode.Next;
                        nextTrain = nextNode.Value;
                    }
                }
            }
        }

        //================================================================================================//
        //
        // Get next time
        //
        public float NextTime => Count == 0 ? -1.0f : First.Value.StartTime.Value;

        //================================================================================================//
        //
        // Get all trains with time < present time and remove these from list
        // Skip trains which have a valid 'formedof' set
        //

        public Collection<AITrain> GetTrains(float reqTime)
        {
            Collection<AITrain> itemList = new Collection<AITrain>();

            bool itemsCollected = false;
            LinkedListNode<AITrain> nextNode = this.First;
            LinkedListNode<AITrain> prevNode;

            while (!itemsCollected && nextNode != null)
            {
                if (nextNode.Value.StartTime.Value <= reqTime)
                {
                    itemList.Add(nextNode.Value);
                    prevNode = nextNode;
                    nextNode = prevNode.Next;
                    this.Remove(prevNode);
                }
                else
                {
                    itemsCollected = true;
                }
            }
            return (itemList);
        }

        public Collection<TTTrain> GetTTTrains(float reqTime)
        {
            Collection<TTTrain> itemList = new Collection<TTTrain>();

            bool itemsCollected = false;
            LinkedListNode<AITrain> nextNode = this.First;
            LinkedListNode<AITrain> prevNode;

            while (!itemsCollected && nextNode != null)
            {
                if (nextNode.Value.StartTime.Value <= reqTime)
                {
                    TTTrain nextTrain = nextNode.Value as TTTrain;
                    if (nextTrain.FormedOf < 0 && nextTrain.TrainType != TrainType.Player)
                    {
                        itemList.Add(nextTrain);
                        prevNode = nextNode;
                        nextNode = prevNode.Next;
                        this.Remove(prevNode);
                    }
                    else
                    {
                        nextNode = nextNode.Next;
                    }
                }
                else
                {
                    itemsCollected = true;
                }
            }

            return (itemList);
        }

        public void RemovePlayerTrain()
        {
            LinkedListNode<AITrain> nextNode = this.First;
            LinkedListNode<AITrain> prevNode;
            bool playerFound = false;

            while (nextNode != null && !playerFound)
            {
                if (nextNode.Value.TrainType == TrainType.Player || nextNode.Value.TrainType == TrainType.PlayerIntended)
                {
                    prevNode = nextNode;
                    nextNode = prevNode.Next;
                    this.Remove(prevNode);
                    playerFound = true;
                }
                else
                {
                    nextNode = nextNode.Next;
                }
            }
        }

        //================================================================================================//
        //
        // Get unstarted train by number and remove it from startlist if required
        //

        public TTTrain GetNotStartedTTTrainByNumber(int reqNumber, bool remove)
        {
            LinkedListNode<AITrain> AITrainNode = First;
            while (AITrainNode != null)
            {
                TTTrain tttrain = AITrainNode.Value as TTTrain;
                if (tttrain.Number == reqNumber || tttrain.OrgAINumber == reqNumber)
                {
                    if (remove)
                        Remove(AITrainNode);
                    return (tttrain);
                }
                else
                {
                    AITrainNode = AITrainNode.Next;
                }
            }
            return (null);
        }

        //================================================================================================//
        //
        // Get unstarted train by number and remove it from startlist if required
        //

        public TTTrain GetNotStartedTTTrainByName(string reqName, bool remove)
        {
            LinkedListNode<AITrain> AITrainNode = First;
            while (AITrainNode != null)
            {
                if (string.Equals(AITrainNode.Value.Name, reqName, StringComparison.OrdinalIgnoreCase))
                {
                    TTTrain reqTrain = AITrainNode.Value as TTTrain;
                    if (remove)
                        Remove(AITrainNode);
                    return (reqTrain);
                }
                else
                {
                    AITrainNode = AITrainNode.Next;
                }
            }
            return (null);
        }

    }
}
