trigger:
  batch: 
    'true'
  branches:
    include:
    - azure-pipelines

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '#Revision
    $Revision = "test"
    #set Content
    Set-Content ./Program/Revision.txt "1.3.1-$(Build.BuildId)-$Revision"'
    errorActionPreference: 'silentlyContinue'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: './Program/'
    includeRootFolder: true 
    verbose: true # Optional

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
      
      Write-Host "Hello World"
      Write-Host "$(Build.BuildId)"'
      
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/.zip'
    ConnectedServiceNameARM: 'Visual Studio Enterprise(81c98ddc-0e66-422e-af90-10337e5c2352)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'ultimaterails'
    ContainerName: 'ci-builds'
    BlobPrefix: 'ci'

