<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>Free Train Simulator Online Player Library</Description>
		<AssemblyTitle>Free Train Simulator Online Player Library</AssemblyTitle>
		<OutputPath>..\..\Program</OutputPath>
		<Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="MagicOnion.Abstractions" Version="7.10.1" />
		<PackageReference Include="MagicOnion.Client" Version="7.10.1" />
		<PackageReference Include="MagicOnion.Serialization.MemoryPack" Version="7.10.1-preview" />
		<PackageReference Include="MemoryPack" Version="1.21.4" />
		<PackageReference Include="MessagePack" Version="3.1.7" />
	</ItemGroup>
</Project>
