<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <Description>Free Train Simulator Toolbox</Description>
    <AssemblyTitle>Free Train Simulator Toolbox</AssemblyTitle>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputPath>..\..\Program</OutputPath>
    <ApplicationIcon>..\FTS.ico</ApplicationIcon>
    <RootNamespace>FreeTrainSimulator.Toolbox</RootNamespace>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.74.1" />
    <PackageReference Include="GetText.NET" Version="11.0.10-preview.1" />
    <PackageReference Include="GetText.NET.Wpf" Version="11.0.10-preview.1" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FreeTrainSimulator.Common\FreeTrainSimulator.Common.csproj" />
    <ProjectReference Include="..\FreeTrainSimulator.Models\FreeTrainSimulator.Models.csproj" />
    <ProjectReference Include="..\FreeTrainSimulator.Graphics\FreeTrainSimulator.Graphics.csproj" />
  </ItemGroup>
</Project>