/* Generated by MyraPad at 9/11/2022 5:35:03 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

using Image = Myra.Graphics2D.UI.Image;

namespace Toolbox.YO2
{
	partial class M_3DEquipViewer: Window
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("../Content/3dview.JPG");

			
			Title = "3D Equipment View";
			DragDirection = Myra.Graphics2D.UI.DragDirection.None;
			Left = 301;
			Width = 760;
			Height = 608;
			Id = "M_Equip3DViewer";
			Content = image1;
		}

		
	}
}
