/* Generated by MyraPad at 9/11/2022 4:56:27 PM */
using Orts.Models.Simplified;

namespace Toolbox.YO2
{
	public partial class M_Equip
	{
		public M_Equip()
		{
			BuildUI();

            // Get equip directory list


        }
	}
}