/* Generated by MyraPad at 9/11/2022 5:40:42 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

using SolidBrush = Myra.Graphics2D.Brushes.SolidBrush;
using Color = Microsoft.Xna.Framework.Color;

namespace Toolbox.YO2
{
	partial class M_Equip: Window
	{
		private void BuildUI()
		{
			var textBox1 = new TextBox();
			textBox1.Text = "Total:";

			_EqpTotal = new TextBox();
			_EqpTotal.GridColumn = 1;
			_EqpTotal.Id = "_EqpTotal";

			var textBox2 = new TextBox();
			textBox2.Text = "Type:";
			textBox2.GridRow = 1;

			var listItem1 = new ListItem();
			listItem1.Text = "All                        ";

			var listItem2 = new ListItem();
			listItem2.Text = "Electric                ";

			var listItem3 = new ListItem();
			listItem3.Text = "Diesel                  ";

			var listItem4 = new ListItem();
			listItem4.Text = "Steam                  ";

			var listItem5 = new ListItem();
			listItem5.Text = "Carriage               ";

			var listItem6 = new ListItem();
			listItem6.Text = "Freight                 ";

			var listItem7 = new ListItem();
			listItem7.Text = "Tender                 ";

			_EqpType = new ComboBox();
			_EqpType.GridColumn = 1;
			_EqpType.GridRow = 1;
			_EqpType.Id = "_EqpType";
			_EqpType.Items.Add(listItem1);
			_EqpType.Items.Add(listItem2);
			_EqpType.Items.Add(listItem3);
			_EqpType.Items.Add(listItem4);
			_EqpType.Items.Add(listItem5);
			_EqpType.Items.Add(listItem6);
			_EqpType.Items.Add(listItem7);

			var textBox3 = new TextBox();
			textBox3.Text = "Coupling:";
			textBox3.GridRow = 2;

			var listItem8 = new ListItem();
			listItem8.Text = "All                       ";

			var listItem9 = new ListItem();
			listItem9.Text = "Chain                  ";

			var listItem10 = new ListItem();
			listItem10.Text = "Automatic            ";

			var listItem11 = new ListItem();
			listItem11.Text = "Bar                       ";

			_EqpCoupling = new ComboBox();
			_EqpCoupling.GridColumn = 1;
			_EqpCoupling.GridRow = 2;
			_EqpCoupling.Id = "_EqpCoupling";
			_EqpCoupling.Items.Add(listItem8);
			_EqpCoupling.Items.Add(listItem9);
			_EqpCoupling.Items.Add(listItem10);
			_EqpCoupling.Items.Add(listItem11);

			var textBox4 = new TextBox();
			textBox4.Text = "ERA:";
			textBox4.GridRow = 3;

			_EqpERA = new TextBox();
			_EqpERA.GridColumn = 1;
			_EqpERA.GridRow = 3;
			_EqpERA.Id = "_EqpERA";

			var textBox5 = new TextBox();
			textBox5.Text = "Search:";
			textBox5.GridRow = 4;

			_EqpSearch = new TextBox();
			_EqpSearch.GridColumn = 1;
			_EqpSearch.GridRow = 4;
			_EqpSearch.Id = "_EqpSearch";

			var textBox6 = new TextBox();
			textBox6.Text = "# to Add";
			textBox6.GridRow = 5;

			_EqpNumAdd = new TextBox();
			_EqpNumAdd.GridColumn = 1;
			_EqpNumAdd.GridRow = 5;
			_EqpNumAdd.ZIndex = -4;
			_EqpNumAdd.Id = "_EqpNumAdd";

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			grid1.BorderThickness = new Thickness(1);
			grid1.Border = new SolidBrush("#FFFFFFFF");
			grid1.Widgets.Add(textBox1);
			grid1.Widgets.Add(_EqpTotal);
			grid1.Widgets.Add(textBox2);
			grid1.Widgets.Add(_EqpType);
			grid1.Widgets.Add(textBox3);
			grid1.Widgets.Add(_EqpCoupling);
			grid1.Widgets.Add(textBox4);
			grid1.Widgets.Add(_EqpERA);
			grid1.Widgets.Add(textBox5);
			grid1.Widgets.Add(_EqpSearch);
			grid1.Widgets.Add(textBox6);
			grid1.Widgets.Add(_EqpNumAdd);

			_EqpAB_button = new TextButton();
			_EqpAB_button.Text = "Begining";
			_EqpAB_button.TextColor = Color.Black;
			_EqpAB_button.BorderThickness = new Thickness(1);
			_EqpAB_button.Background = new SolidBrush("#D9D9D9FF");
			_EqpAB_button.Border = new SolidBrush("#5BC6FAFF");
			_EqpAB_button.Id = "_EqpAB_button";

			_EqpAC_button = new TextButton();
			_EqpAC_button.Text = "Current";
			_EqpAC_button.TextColor = Color.Black;
			_EqpAC_button.BorderThickness = new Thickness(1);
			_EqpAC_button.Background = new SolidBrush("#D9D9D9FF");
			_EqpAC_button.Border = new SolidBrush("#5BC6FAFF");
			_EqpAC_button.Id = "_EqpAC_button";

			_EqpAE_button = new TextButton();
			_EqpAE_button.Text = " End ";
			_EqpAE_button.TextColor = Color.Black;
			_EqpAE_button.BorderThickness = new Thickness(1);
			_EqpAE_button.Background = new SolidBrush("#D9D9D9FF");
			_EqpAE_button.Border = new SolidBrush("#5BC6FAFF");
			_EqpAE_button.Id = "_EqpAE_button";

			_EqpRB_button = new TextButton();
			_EqpRB_button.Text = "Random ";
			_EqpRB_button.TextColor = Color.Black;
			_EqpRB_button.BorderThickness = new Thickness(1);
			_EqpRB_button.Background = new SolidBrush("#D9D9D9FF");
			_EqpRB_button.Border = new SolidBrush("#5BC6FAFF");
			_EqpRB_button.Id = "_EqpRB_button";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Widgets.Add(_EqpAB_button);
			horizontalStackPanel1.Widgets.Add(_EqpAC_button);
			horizontalStackPanel1.Widgets.Add(_EqpAE_button);
			horizontalStackPanel1.Widgets.Add(_EqpRB_button);

			_EqpList = new ListBox();
			_EqpList.Width = 249;
			_EqpList.Height = 579;
			_EqpList.Id = "_EqpList";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_EqpList);

			
			Title = "Equipment";
			DragDirection = Myra.Graphics2D.UI.DragDirection.None;
			Left = 556;
			Width = 250;
			Height = 608;
			Id = "M_Equip";
			Content = verticalStackPanel1;
		}

		
		public TextBox _EqpTotal;
		public ComboBox _EqpType;
		public ComboBox _EqpCoupling;
		public TextBox _EqpERA;
		public TextBox _EqpSearch;
		public TextBox _EqpNumAdd;
		public TextButton _EqpAB_button;
		public TextButton _EqpAC_button;
		public TextButton _EqpAE_button;
		public TextButton _EqpRB_button;
		public ListBox _EqpList;
	}
}
