/* Generated by MyraPad at 9/7/2022 4:14:28 PM */
/* Generated by MyraPad at 9/6/2022 3:40:08 PM */
using System;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Input;

using Myra.Graphics2D.UI;
using Orts.Models.Simplified;

using Point = Microsoft.Xna.Framework.Point;

namespace Toolbox.YO2
{
    public partial class M_MainWindow
    {

        private GameWindow gameWindow;
        private readonly M_ViewWindow m_ViewWindow = new M_ViewWindow();
//        private readonly M_OpenWindow m_OpenWindow = new M_OpenWindow();
        private readonly DebugWindow m_DebugWindow = new DebugWindow();
        private M_OpenWindow m_OpenWindow;


        

        public M_MainWindow(GameWindow gameWindow)
        {
            this.gameWindow = gameWindow;
            BuildUI();
           
            menuItemSelect.Selected += SelectItemOnDown;
            menuItemAbout.Selected += AboutItemOnDown;
            menuItemView.Selected += ViewItemOnDown;
            menuItemDebug.Selected += MenuItemDebug_Selected;

            m_OpenWindow = new M_OpenWindow(gameWindow);
          
          
        }

        private void MenuItemDebug_Selected(object sender, EventArgs e)
        {

            m_DebugWindow.ShowModal(Desktop);
        }

        


        private void AboutItemOnDown(object sender, EventArgs eventArgs)
        {
            var messageBox = Myra.Graphics2D.UI.Dialog.CreateMessageBox("YardOffice", "Myra " + Myra.MyraEnvironment.Version);

            messageBox.ShowModal(Desktop);
        }

       

        private void ViewItemOnDown(object sender, EventArgs eventArgs)
        {
            m_ViewWindow.ShowModal(Desktop, new Point(300, 21));
        }

        private void SelectItemOnDown(object sender, EventArgs eventArgs)
        {
            m_OpenWindow.Show(Desktop);
        }

    }
}