/* Generated by MyraPad at 9/7/2022 4:14:28 PM */
/* Generated by MyraPad at 9/6/2022 3:40:08 PM */
using System;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Input;

using Point = Microsoft.Xna.Framework.Point;

namespace Toolbox.YO2
{
    public partial class M_MainWindow
    {
        private readonly M_ViewWindow m_ViewWindow = new M_ViewWindow();
        private readonly M_OpenWindow m_OpenWindow = new M_OpenWindow();
        private readonly DebugWindow m_DebugWindow = new DebugWindow();
    

        public M_MainWindow()
        {
            BuildUI();

            menuItemSelect.Selected += SelectItemOnDown;
            menuItemQuit.Selected += QuitItemOnDown;
            menuItemAbout.Selected += AboutItemOnDown;
            menuItemView.Selected += ViewItemOnDown;
            menuItemDebug.Selected += MenuItemDebug_Selected;
          
          
        }

        private void MenuItemDebug_Selected(object sender, EventArgs e)
        {

            m_DebugWindow.ShowModal(Desktop);
        }

        private void QuitItemOnDown(object sender, EventArgs genericEventArgs)
        {
            GameWindow.Instance.Exit();
        }


        private void AboutItemOnDown(object sender, EventArgs eventArgs)
        {
            var messageBox = Myra.Graphics2D.UI.Dialog.CreateMessageBox("YardOffice", "Myra " + Myra.MyraEnvironment.Version);

            messageBox.ShowModal(Desktop);
        }

       

        private void ViewItemOnDown(object sender, EventArgs eventArgs)
        {
            m_ViewWindow.Show(Desktop, new Point(300, 21));
        }

        private void SelectItemOnDown(object sender, EventArgs eventArgs)
        {
            m_OpenWindow.ShowModal(Desktop);
        }

    }
}