/* Generated by MyraPad at 9/7/2022 4:14:28 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Toolbox.YO2
{
	partial class M_MainWindow: VerticalStackPanel
	{
		private void BuildUI()
		{
			menuItemSelect = new MenuItem();
			menuItemSelect.Text = "Se&Lect";
			menuItemSelect.Id = "menuItemSelect";

			menuItemQuit = new MenuItem();
			menuItemQuit.Text = "&Quit";
			menuItemQuit.Id = "menuItemQuit";

			menuItemRoute = new MenuItem();
			menuItemRoute.Text = "&Route";
			menuItemRoute.Id = "menuItemRoute";
			menuItemRoute.Items.Add(menuItemSelect);
			menuItemRoute.Items.Add(menuItemQuit);

			menuItemConsist = new MenuItem();
			menuItemConsist.Text = "&Consist";
			menuItemConsist.Id = "menuItemConsist";

			menuItemEng = new MenuItem();
			menuItemEng.Text = "&Eng";
			menuItemEng.Id = "menuItemEng";

			menuItemReplace = new MenuItem();
			menuItemReplace.Text = "&Replace";
			menuItemReplace.Id = "menuItemReplace";

			menuItemView = new MenuItem();
			menuItemView.Text = "&View";
			menuItemView.Id = "menuItemView";

			menuItem3DView = new MenuItem();
			menuItem3DView.Text = "&3D View";
			menuItem3DView.Id = "menuItem3DView";

			menuItemSettings = new MenuItem();
			menuItemSettings.Text = "&Settings";
			menuItemSettings.Id = "menuItemSettings";

			menuItemAbout = new MenuItem();
			menuItemAbout.Text = "About";
			menuItemAbout.Id = "menuItemAbout";

			menuItemHelp = new MenuItem();
			menuItemHelp.Text = "&Help";
			menuItemHelp.Id = "menuItemHelp";
			menuItemHelp.Items.Add(menuItemAbout);

			MmainMenu = new HorizontalMenu();
			MmainMenu.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			MmainMenu.Id = "MmainMenu";
			MmainMenu.Items.Add(menuItemRoute);
			MmainMenu.Items.Add(menuItemConsist);
			MmainMenu.Items.Add(menuItemEng);
			MmainMenu.Items.Add(menuItemReplace);
			MmainMenu.Items.Add(menuItemView);
			MmainMenu.Items.Add(menuItem3DView);
			MmainMenu.Items.Add(menuItemSettings);
			MmainMenu.Items.Add(menuItemHelp);

			var horizontalSeparator1 = new HorizontalSeparator();

			M_MainPanel = new Panel();
			M_MainPanel.Id = "M_MainPanel";

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(MmainMenu);
			Widgets.Add(horizontalSeparator1);
			Widgets.Add(M_MainPanel);
		}

		
		public MenuItem menuItemSelect;
		public MenuItem menuItemQuit;
		public MenuItem menuItemRoute;
		public MenuItem menuItemConsist;
		public MenuItem menuItemEng;
		public MenuItem menuItemReplace;
		public MenuItem menuItemView;
		public MenuItem menuItem3DView;
		public MenuItem menuItemSettings;
		public MenuItem menuItemAbout;
		public MenuItem menuItemHelp;
		public HorizontalMenu MmainMenu;
		public Panel M_MainPanel;
	}
}
