/* Generated by MyraPad at 9/7/2022 4:14:03 PM */


using System.Linq;

using Microsoft.Xna.Framework;

using Myra.Graphics2D.UI;
using Orts.Models.Simplified;
using Orts.Formats.Msts;
using System.Drawing.Text;

using ListItem = Myra.Graphics2D.UI.ListItem;

namespace Toolbox.YO2
{
	public partial class M_OpenWindow
	{

         

		public M_OpenWindow()
		{
            

            BuildUI();

            // Populate Routes
            // 

            
            foreach (Folder folder in GameWindow.Instance.folders)
            {
                var listItem = new ListItem();
                listItem.Text = folder.Name;
                listItem.Color = Color.White;
                _OpenWin_List.Items.Add(listItem);
            }


            _OpenWin_Cancel_button.Click += _OpenWin_Cancel_button_Click;
            _OpenWin_Load_button.Click += _OpenWin_Load_button_Click;


 
            
        }

        private void _OpenWin_Load_button_Click(object sender, System.EventArgs e)
        {
            var routeselected = " ";

            if (_OpenWin_List.SelectedItem == null)
                routeselected = "Route not Selected";
            else
            {
                foreach (Folder folder in GameWindow.Instance.folders)
                {
                    if (folder.Name == _OpenWin_List.SelectedItem.Text)
                    {
                        routeselected = folder.Name;
                        break;
                    }
                }
            }

            var messageBox = Myra.Graphics2D.UI.Dialog.CreateMessageBox("YardOffice", routeselected);

            messageBox.ShowModal(Desktop);

            
        }

        private void _OpenWin_Cancel_button_Click(object sender, System.EventArgs e)
        {
            base.Result = false;
            Close();
        }

        
    }
}