/* Generated by MyraPad at 9/7/2022 8:35:34 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

using Color = Microsoft.Xna.Framework.Color;
using SolidBrush = Myra.Graphics2D.Brushes.SolidBrush;
using Image = Myra.Graphics2D.UI.Image;

namespace Toolbox.YO2
{
	partial class M_OpenWindow: Window
	{
		private void BuildUI()
		{
			var image1 = new Image();
			image1.Renderable = MyraEnvironment.DefaultAssetManager.Load<TextureRegion>("../Content/TitleBarWindow.png");

			var textButton1 = new TextButton();
			textButton1.Text = "                                               Search                            " +
    "                      ";
			textButton1.TextColor = Color.Black;
			textButton1.BorderThickness = new Thickness(2);
			textButton1.Background = new SolidBrush("#D9D9D9FF");
			textButton1.Border = new SolidBrush("#FFFFFFFF");

			var listItem1 = new ListItem();
			listItem1.Text = "Route1";
			listItem1.Color = Color.White;

			var listItem2 = new ListItem();
			listItem2.Text = "Route2";
			listItem2.Color = Color.White;

			var listItem3 = new ListItem();
			listItem3.Text = "Route3";
			listItem3.Color = Color.White;

			var listItem4 = new ListItem();
			listItem4.Text = "Route4";
			listItem4.Color = Color.White;

			var listItem5 = new ListItem();
			listItem5.Text = "Route5";
			listItem5.Color = Color.White;

			var listItem6 = new ListItem();
			listItem6.Text = "Route6";
			listItem6.Color = Color.White;

			var listItem7 = new ListItem();
			listItem7.Text = "Route7";
			listItem7.Color = Color.White;

			var listItem8 = new ListItem();
			listItem8.Text = "Route8";
			listItem8.Color = Color.White;

			var listItem9 = new ListItem();
			listItem9.Text = "Route9";
			listItem9.Color = Color.White;

			var listBox1 = new ListBox();
			listBox1.Width = 540;
			listBox1.Items.Add(listItem1);
			listBox1.Items.Add(listItem2);
			listBox1.Items.Add(listItem3);
			listBox1.Items.Add(listItem4);
			listBox1.Items.Add(listItem5);
			listBox1.Items.Add(listItem6);
			listBox1.Items.Add(listItem7);
			listBox1.Items.Add(listItem8);
			listBox1.Items.Add(listItem9);

			var textButton2 = new TextButton();
			textButton2.Text = "                                        Load                                     " +
    "    ";
			textButton2.BorderThickness = new Thickness(2);
			textButton2.Background = new SolidBrush("#4BD961FF");
			textButton2.Border = new SolidBrush("#FFFFFFFF");

			M_OpenWin_Cancel = new TextButton();
			M_OpenWin_Cancel.Text = "    Cancel    ";
			M_OpenWin_Cancel.BorderThickness = new Thickness(2);
			M_OpenWin_Cancel.Background = new SolidBrush("#FE3930FF");
			M_OpenWin_Cancel.Border = new SolidBrush("#FFFFFFFF");
			M_OpenWin_Cancel.Id = "M_OpenWin_Cancel";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			horizontalStackPanel1.Widgets.Add(textButton2);
			horizontalStackPanel1.Widgets.Add(M_OpenWin_Cancel);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Widgets.Add(image1);
			verticalStackPanel1.Widgets.Add(textButton1);
			verticalStackPanel1.Widgets.Add(listBox1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);

			
			Title = "";
			Left = 408;
			Top = 7;
			Id = "M_OpenWindow";
			Content = verticalStackPanel1;
		}

		
		public TextButton M_OpenWin_Cancel;
	}
}
