/* Generated by MyraPad at 9/7/2022 4:14:03 PM */


using System.Linq;

using Microsoft.Xna.Framework;

using Myra.Graphics2D.UI;
using Orts.Models.Simplified;
using Orts.Formats.Msts;
using System.Drawing.Text;

using ListItem = Myra.Graphics2D.UI.ListItem;
using System.Collections.Generic;
using System.Windows.Forms;

namespace Toolbox.YO2
{
	public partial class M_OpenWindow
	{

        

        public M_OpenWindow()
		{
            

            BuildUI();

            // Populate Routes
            // 


            foreach (Folder folder in GameWindow.Instance.folders)
            {
                var listItem = new ListItem();
                listItem.Text = folder.Name;
                listItem.Color = Color.White;
                _OpenWin_List.Items.Add(listItem);
            }


            _OpenWin_Cancel_button.Click += _OpenWin_Cancel_button_Click;
            _OpenWin_Load_button.Click += _OpenWin_Load_button_Click;


 
            
        }

        

        private async void _OpenWin_Load_button_Click(object sender, System.EventArgs e)
        {
            
            var routeselected = " ";
            int count_i = 0;
            if (_OpenWin_List.SelectedItem == null)
                routeselected = "Route not Selected";
            else
            {
                foreach (Folder folder in GameWindow.Instance.folders)
                {
                    if (folder.Name == _OpenWin_List.SelectedItem.Text)
                    {
                        await GameWindow.Instance.LoadConsists(folder).ConfigureAwait(true);
                        routeselected = folder.Name;
                        var mw = new M_Trains();
                        var me = new M_Equip();
                        var m3d = new M_3DEquipViewer();
                        ;
                        foreach (Consist consist in GameWindow.Instance.consists)
                        {
                            var listItem = new ListItem();
                            listItem.Text = consist.Name;
                            listItem.Color = Color.White;
                            mw._ConsistList.Items.Add(listItem);
                            count_i++;
                        }                        
                        mw._TrainCount.Text = count_i.ToString();
                        mw.Show(Desktop, new Point(1, 21));
                        me.Show(Desktop, new Point(252, 21));
                        m3d.Show(Desktop, new Point(502, 21));
                        break;
                    }
                }
            }

            var messageBox = Dialog.CreateMessageBox("YardOffice", routeselected + " Number of Consists = " + count_i.ToString());


            messageBox.ShowModal(Desktop);

            Close();

        }

        private void _OpenWin_Cancel_button_Click(object sender, System.EventArgs e)
        {
            base.Result = false;
            Close();
        }

    }
}