/* Generated by MyraPad at 9/7/2022 4:14:03 PM */


using System.Linq;

using Microsoft.Xna.Framework;

using Myra.Graphics2D.UI;
using Orts.Models.Simplified;

namespace Toolbox.YO2
{
	public partial class M_OpenWindow
	{
		public M_OpenWindow()
		{

            BuildUI();

            // Populate Routes
            // 

            var listItem = new Myra.Graphics2D.UI.ListItem();
            foreach (Folder folder in GameWindow.Instance.folders)
            { 
                listItem.Text = folder.Name;
                listItem.Color = Color.White;
                _OpenWin_List.Items.Add(listItem);
            }


            _OpenWin_Cancel_button.Click += _OpenWin_Cancel_button_Click;
            
        }

        private void _OpenWin_Cancel_button_Click(object sender, System.EventArgs e)
        {
            base.Result = false;
            Close();
        }

        
    }
}