/* Generated by MyraPad at 9/14/2022 4:57:52 PM */
namespace Toolbox.YO2
{
	public partial class M_ProgressBar
	{
		public M_ProgressBar()
		{
			BuildUI();

         //   this.TitleGrid.Visible = false;
		}
	}
}