/* Generated by MyraPad at 9/16/2022 10:48:51 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

namespace Toolbox.YO2
{
	partial class M_ProgressBar: Window
	{
		private void BuildUI()
		{
			m_progressBar_Text = new Label();
			m_progressBar_Text.Text = "                Loading Equipment";
			m_progressBar_Text.Width = 300;
			m_progressBar_Text.Id = "m_progressBar_Text";

			m_progressBar_tb = new TextBox();
			m_progressBar_tb.Width = 300;
			m_progressBar_tb.Id = "m_progressBar_tb";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Widgets.Add(m_progressBar_Text);
			verticalStackPanel1.Widgets.Add(m_progressBar_tb);

			
			Title = "";
			DragDirection = Myra.Graphics2D.UI.DragDirection.None;
			Left = 531;
			Top = 88;
			Id = "m_progressBar";
			Content = verticalStackPanel1;
		}

		
		public Label m_progressBar_Text;
		public TextBox m_progressBar_tb;
	}
}
