/* Generated by MyraPad at 9/11/2022 2:11:15 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;

#if MONOGAME || FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#elif STRIDE
using Stride.Core.Mathematics;
#else
using System.Drawing;
using System.Numerics;
#endif

using SolidBrush = Myra.Graphics2D.Brushes.SolidBrush;

namespace Toolbox.YO2
{
	partial class M_Trains: Window
	{
		private void BuildUI()
		{
			var textBox1 = new TextBox();
			textBox1.Text = "Count:";

			_TrainCount = new TextBox();
			_TrainCount.GridColumn = 1;
			_TrainCount.Id = "_TrainCount";

			var textBox2 = new TextBox();
			textBox2.Text = "Show:";
			textBox2.GridRow = 1;

			var listItem1 = new ListItem();
			listItem1.Text = "Train Consists    ";

			var listItem2 = new ListItem();
			listItem2.Text = "Activity Consists ";

			_TrainShow = new ComboBox();
			_TrainShow.GridColumn = 1;
			_TrainShow.GridRow = 1;
			_TrainShow.Id = "_TrainShow";
			_TrainShow.Items.Add(listItem1);
			_TrainShow.Items.Add(listItem2);

			var textBox3 = new TextBox();
			textBox3.Text = "Filter:";
			textBox3.GridRow = 2;

			var listItem3 = new ListItem();
			listItem3.Text = "All                       ";

			var listItem4 = new ListItem();
			listItem4.Text = "Broken               ";

			var listItem5 = new ListItem();
			listItem5.Text = "Unsaved            ";

			var listItem6 = new ListItem();
			listItem6.Text = "Last Query";

			_TrainFilter = new ComboBox();
			_TrainFilter.GridColumn = 1;
			_TrainFilter.GridRow = 2;
			_TrainFilter.Id = "_TrainFilter";
			_TrainFilter.Items.Add(listItem3);
			_TrainFilter.Items.Add(listItem4);
			_TrainFilter.Items.Add(listItem5);
			_TrainFilter.Items.Add(listItem6);

			var grid1 = new Grid();
			grid1.ShowGridLines = true;
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Part,
				Value = 2,
			});
			grid1.BorderThickness = new Thickness(1);
			grid1.Border = new SolidBrush("#FFFFFFFF");
			grid1.Widgets.Add(textBox1);
			grid1.Widgets.Add(_TrainCount);
			grid1.Widgets.Add(textBox2);
			grid1.Widgets.Add(_TrainShow);
			grid1.Widgets.Add(textBox3);
			grid1.Widgets.Add(_TrainFilter);

			_ConsistList = new ListBox();
			_ConsistList.Width = 249;
			_ConsistList.Height = 600;
			_ConsistList.Id = "_ConsistList";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			verticalStackPanel1.Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(_ConsistList);

			
			Title = "Trains";
			DragDirection = Myra.Graphics2D.UI.DragDirection.None;
			Left = 362;
			Width = 250;
			Height = 608;
			Id = "M_Trains";
			Content = verticalStackPanel1;
		}

		
		public TextBox _TrainCount;
		public ComboBox _TrainShow;
		public ComboBox _TrainFilter;
		public ListBox _ConsistList;
	}
}
