/* Generated by MyraPad at 9/6/2022 4:00:08 PM */

namespace Toolbox.YO2
{
	public partial class M_ViewWindow
	{
		public M_ViewWindow()
		{
			BuildUI();

            _SaveWindowView.Click += _SaveWindowView_Click;
        }

        private void _SaveWindowView_Click(object sender, System.EventArgs e)
        {
            base.Result = false;
            Close();
        }

    }
}