/* Generated by MyraPad at 9/6/2022 4:00:08 PM */
using System;

using Microsoft.Xna.Framework;

namespace Toolbox.YO2
{
	public partial class M_ViewWindow
	{
		public M_ViewWindow()
		{
			BuildUI();
		}

        
    }
}