<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <Description>Free Train Simulator Menu</Description>
    <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
    <AssemblyTitle>Free Train Simulator Menu</AssemblyTitle>
    <OutputPath>..\..\Program</OutputPath>
    <ApplicationIcon>..\FTS.ico</ApplicationIcon>
    <RootNamespace>FreeTrainSimulator.Menu</RootNamespace>
    <Configurations>Debug;Release;CodeAnalysis;UpdateContentVersion</Configurations>
		<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.5.1" />
    <PackageReference Include="GetText.NET" Version="11.0.10-preview.1" />
    <PackageReference Include="GetText.NET.WindowsForms" Version="11.0.10-preview.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FreeTrainSimulator.Models.Imported\FreeTrainSimulator.Models.Imported.csproj" />
    <ProjectReference Include="..\FreeTrainSimulator.Online\FreeTrainSimulator.Online.csproj" />
    <ProjectReference Include="..\FreeTrainSimulator.Updater\FreeTrainSimulator.Updater.csproj" />
  </ItemGroup>
</Project>